# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ec2-instance
  description: Terraform module for provisioning a general purpose EC2 host
  homepage: https://cloudposse.com/accelerate
  topics: aws, ec2, security, instance, ansible, terraform, terraform-modules, hcl2

